# Generated by Django 3.2.3 on 2021-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BD',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=50)),
                ('telemovel', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pergunta1', models.CharField(max_length=50)),
                ('pergunta2', models.CharField(max_length=50)),
                ('pergunta3', models.CharField(max_length=50)),
                ('pergunta4', models.CharField(max_length=50)),
                ('pergunta5', models.CharField(max_length=50)),
                ('pergunta6', models.CharField(max_length=50)),
                ('pergunta7', models.CharField(max_length=50)),
                ('pergunta8', models.CharField(max_length=50)),
                ('pergunta9', models.CharField(max_length=50)),
                ('pergunta10', models.CharField(max_length=50)),
            ],
        ),
    ]
