# Generated by Django 3.2.3 on 2021-06-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatfit', '0002_auto_20210606_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='compreensao',
            field=models.IntegerField(default=2),
        ),
    ]
