# Generated by Django 3.2.3 on 2021-06-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatfit', '0003_alter_comment_compreensao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='compreensao',
            field=models.IntegerField(default=0),
        ),
    ]
