# Generated by Django 3.2.3 on 2021-06-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatfit', '0004_alter_comment_compreensao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('sala', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.IntegerField()),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='eatfit.aulas')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='eatfit.aulas')),
            ],
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnome', models.CharField(max_length=64)),
                ('unome', models.CharField(max_length=64)),
                ('atividade', models.ManyToManyField(blank=True, related_name='Alunos', to='eatfit.Atividades')),
            ],
        ),
    ]
