# Generated by Django 3.2.3 on 2021-07-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatfit', '0006_auto_20210702_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='professor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Professor', to='eatfit.professor'),
            preserve_default=False,
        ),
    ]
